# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-13 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prof_picture',
            field=models.ImageField(default='kent.jpg', upload_to='picture/'),
        ),
    ]
