# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-02-12 08:27
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0005_auto_20200212_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
